name: dask-nlp
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.9.7
  - coiled
  - pandas==1.4.1
  - dask[complete]==2022.02.0
  - nltk==3.6.5
  - spacy==3.2.0
  - scipy
  - scikit-learn
  - pyarrow
  - fastparquet
  - jupyterlab
  - dask-labextension
  - ipykernel
  - s3fs==2021.11.0
  - lz4
  - numpy==1.21.5
  - ipython
  - ipywidgets
  - ujson==4.2.0
  - gensim[distributed]
  - dask-ml
  - xgboost==1.5.0
  - pip:
    - pymongo[srv]
    - git+https://github.com/coiled/dask-mongo.git
